cleanup

diff --git a/startup b/startup
--- a/startup
+++ b/startup
@@ -32,19 +32,19 @@ last_timestamp=0
 ts_diff=$((${timestamp}-${last_timestamp}))
 rebuild_needed=n
 
-echo "Last git pull was $ts_diff seconds ago. Automatic pull after $git_check_time seconds..."
-if [ $ts_diff -gt $git_check_time ]; then
-   # can we reach github?
-   echo "Trying to ping github to see if it's reachable..."
-   ping -c 3 github.com
-   if [ $? -eq 0 ]; then
-      git pull || echo "Couldn't git pull.. Are you online? Try again later!"
-      # save timestamp, so we won't try again for awhile...
-      echo "${timestamp}" > .git_timestamp
-   else
-      echo "Can't ping github, skipping automatic 'git pull'. Try it manually!"
-   fi
-fi
+#echo "Last git pull was $ts_diff seconds ago. Automatic pull after $git_check_time seconds..."
+#if [ $ts_diff -gt $git_check_time ]; then
+#   # can we reach github?
+#   echo "Trying to ping github to see if it's reachable..."
+#   ping -c 3 github.com
+#   if [ $? -eq 0 ]; then
+#      git pull || echo "Couldn't git pull.. Are you online? Try again later!"
+#      # save timestamp, so we won't try again for awhile...
+#      echo "${timestamp}" > .git_timestamp
+#   else
+#      echo "Can't ping github, skipping automatic 'git pull'. Try it manually!"
+#   fi
+#fi
 
 #########
 # Add ./lib to the library search path
@@ -58,8 +58,8 @@ export UBSAN_OPTIONS="log_path=logs/ubsan.log"
 
 # rebuild things or exit if failure
 echo "Hang on, we need to compile things... This should only take a moment."
-make clean || exit 2
-make -j${NPROC} world || exit 1
+#make clean || exit 2
+#make -j${NPROC} world || exit 1
 
 echo "Preparing some databases..."
 # Does calldata cache db exist?
