cleanup

diff --git a/startup b/startup
--- a/startup
+++ b/startup
@@ -7,15 +7,17 @@
 # Set a reasonable default for even ten year old machines...
 [ -z "${NPROC}" ] && NPROC=8
 
+# If -g option is passed, use GDB to help debug things
 if [ "$1" == "-g" ]; then
    use_gdb=y
 fi
-
 
 # Add ./lib to the library search path
 export LD_LIBRARY_PATH=./lib:${LD_LIBRARY_PATH}
 
 # Some logging stuff
+####################
+# redirect gcc sanitizer outputs to files
 extern ASAN_OPTIONS="log_path=logs/asan.log"
 extern UBSAN_OPTIONS="log_path=logs/ubsan.log"
 
@@ -35,18 +37,24 @@ last_timestamp=0
 
 ts_diff=$((${timestamp}-${last_timestamp}))
 
-echo "ts_diff: $ts_diff"
+echo "Last git pull was $ts_diff seconds ago. Automatic pull after $git_check_time seconds..."
 if [ $ts_diff -gt $git_check_time ]; then
-   # git pull 
-   git pull || echo "Couldn't git pull.. Are you online? Try again later!"
-
-   # save timestamp, so we won't try again for awhile...
-   echo "${timestamp}" > .git_timestamp
+   # can we reach github?
+   echo "Trying to ping github to see if it's reachable..."
+   ping -c3 github.com
+   if [ $? -eq 0 ]; then
+      git pull || echo "Couldn't git pull.. Are you online? Try again later!"
+      # save timestamp, so we won't try again for awhile...
+      echo "${timestamp}" > .git_timestamp
+   else
+      echo "Can't ping github, skipping automatic 'git pull'. Try it manually!"
+   fi
 fi
+
 # rebuild things or exit if failure
 echo "Hang on, we need to compile things... This should only take a moment."
 make clean || exit 2
-make -j${NPROC} termbox2 world || exit 1
+make -j${NPROC} world || exit 1
 
 # Start ft8goblin, if build was successful
 if [ "${use_gdb}" == "y" ]; then
